version: '3'
services:
  redis-master:
    container_name: redis-master
    build: ./redis-master
    privileged: true
    networks:
      backend:
        ipv4_address: 192.168.0.2
  redis-slave1:
    container_name: redis-slave1
    build: ./redis-slave1
    privileged: true
    depends_on:
      - "redis-master"
    networks:
      backend:
        ipv4_address: 192.168.0.3
  redis-slave2:
    container_name: redis-slave2
    build: ./redis-slave2
    privileged: true
    depends_on:
      - "redis-master"
    networks:
      backend:
        ipv4_address: 192.168.0.4
networks:
    backend:
        name: redis_network
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.0.0/24
                  gateway: "192.168.0.1"